CC=gcc

all: match

match : match.c 
	$(CC) -o match match.c -lpthread
	
matchp : matchp.c 
	$(CC) -o matchp matchp.c -lpthread
	
recherche : recherche.c 
	$(CC) -o recherche recherche.c -lpthread
	
clean:
	rm -rf *.o
	


	
